import type { Pattern } from "../types.js";

// Tier 1: difficulty 1~2
// Characters from: false/true/undefined/NaN/Infinity/digit-arithmetic
// All expressions are pure JSFuck ([]()!+ only) unless noted

const TIER1: Pattern[] = [
  // ===== from "false" (![]+[]) =====
  {
    id: "char_f",
    output: "f",
    role: "char_f",
    expression: "(![]+[])[+[]]",
    pure: true,
    kind: "jsfuck",
    tags: ["tier1", "from_false"],
    description: '"false"[0] = f',
  },
  {
    id: "char_a",
    output: "a",
    role: "char_a",
    expression: "(![]+[])[1]",
    pure: true,
    kind: "jsfuck",
    tags: ["tier1", "from_false"],
    description: '"false"[1] = a',
  },
  {
    id: "char_l",
    output: "l",
    role: "char_l",
    expression: "(![]+[])[2]",
    pure: true,
    kind: "jsfuck",
    tags: ["tier1", "from_false"],
    description: '"false"[2] = l',
  },
  {
    id: "char_s",
    output: "s",
    role: "char_s",
    expression: "(![]+[])[3]",
    pure: true,
    kind: "jsfuck",
    tags: ["tier1", "from_false"],
    description: '"false"[3] = s',
  },
  {
    id: "char_e",
    output: "e",
    role: "char_e",
    expression: "(![]+[])[4]",
    pure: true,
    kind: "jsfuck",
    tags: ["tier1", "from_false"],
    description: '"false"[4] = e',
  },
  // ===== from "true" (!![]+[]) =====
  {
    id: "char_t",
    output: "t",
    role: "char_t",
    expression: "(!![]+[])[+[]]",
    pure: true,
    kind: "jsfuck",
    tags: ["tier1", "from_true"],
    description: '"true"[0] = t',
  },
  {
    id: "char_r",
    output: "r",
    role: "char_r",
    expression: "(!![]+[])[1]",
    pure: true,
    kind: "jsfuck",
    tags: ["tier1", "from_true"],
    description: '"true"[1] = r',
  },
  {
    id: "char_u",
    output: "u",
    role: "char_u",
    expression: "(!![]+[])[2]",
    pure: true,
    kind: "jsfuck",
    tags: ["tier1", "from_true"],
    description: '"true"[2] = u',
  },
  // ===== from "undefined" ([][+[]]+[]) =====
  {
    id: "char_n",
    output: "n",
    role: "char_n",
    expression: "([][+[]]+[])[1]",
    pure: true,
    kind: "jsfuck",
    tags: ["tier1", "from_undefined"],
    description: '"undefined"[1] = n',
  },
  {
    id: "char_d",
    output: "d",
    role: "char_d",
    expression: "([][+[]]+[])[2]",
    pure: true,
    kind: "jsfuck",
    tags: ["tier1", "from_undefined"],
    description: '"undefined"[2] = d',
  },
  {
    id: "char_i",
    output: "i",
    role: "char_i",
    expression: "([][+[]]+[])[5]",
    pure: true,
    kind: "jsfuck",
    tags: ["tier1", "from_undefined"],
    description: '"undefined"[5] = i',
  },
  // ===== from "NaN" (+{}+[]) =====
  {
    id: "char_N_upper",
    output: "N",
    role: "char_N_upper",
    expression: "(+{}+[])[+[]]",
    pure: true,
    kind: "jsfuck",
    tags: ["tier1", "from_nan", "uppercase"],
    description: '"NaN"[0] = N (uppercase)',
  },
  {
    id: "char_a_nan",
    output: "a",
    role: "char_a_nan",
    expression: "(+{}+[])[1]",
    pure: true,
    kind: "jsfuck",
    tags: ["tier1", "from_nan"],
    description: '"NaN"[1] = a (alternate source)',
  },
  // ===== from "Infinity" (1/0+[]) =====
  {
    id: "char_I_upper",
    output: "I",
    role: "char_I_upper",
    expression: "(1/0+[])[+[]]",
    pure: true,
    kind: "jsfuck",
    tags: ["tier1", "from_infinity", "uppercase"],
    description: '"Infinity"[0] = I (uppercase)',
  },
  {
    id: "char_y",
    output: "y",
    role: "char_y",
    expression: "(1/0+[])[7]",
    alternates: ["((+{}+[])+(1/0+[]))[10]"],
    pure: true,
    kind: "jsfuck",
    tags: ["tier1", "from_infinity"],
    description: '"Infinity"[7] = y',
  },
  // ===== from "[object Object]" ([]+{}) =====
  {
    id: "char_O_upper",
    output: "O",
    role: "char_O_upper",
    expression: "([]+{})[8]",
    pure: true,
    kind: "jsfuck",
    tags: ["tier1", "from_obj", "uppercase"],
    description: '"[object Object]"[8] = O (uppercase)',
  },
  {
    id: "char_space",
    output: " ",
    role: "char_space",
    expression: "([]+{})[7]",
    pure: true,
    kind: "jsfuck",
    tags: ["tier1", "symbol"],
    description: '"[object Object]"[7] = space',
  },
  // ===== digit strings via arithmetic =====
  {
    id: "digit_0",
    output: "0",
    role: "digit_0",
    expression: "+[]+[]",
    pure: true,
    kind: "jsfuck",
    tags: ["tier1", "digit"],
    description: "0 as string",
  },
  {
    id: "digit_1",
    output: "1",
    role: "digit_1",
    expression: "+!![]+[]",
    pure: true,
    kind: "jsfuck",
    tags: ["tier1", "digit"],
    description: "1 as string",
  },
  {
    id: "digit_2",
    output: "2",
    role: "digit_2",
    expression: "!![]+!![]+[]",
    pure: true,
    kind: "jsfuck",
    tags: ["tier1", "digit"],
    description: "2 as string",
  },
  {
    id: "digit_3",
    output: "3",
    role: "digit_3",
    expression: "!![]+!![]+!![]+[]",
    pure: true,
    kind: "jsfuck",
    tags: ["tier1", "digit"],
    description: "3 as string",
  },
  {
    id: "digit_4",
    output: "4",
    role: "digit_4",
    expression: "!![]+!![]+!![]+!![]+[]",
    pure: true,
    kind: "jsfuck",
    tags: ["tier1", "digit"],
    description: "4 as string",
  },
  // digit 5-9: non-strict 版（リテラルショートカット）
  {
    id: "digit_5",
    output: "5",
    role: "digit_5",
    expression: '"5"',
    pure: false,
    kind: "jsfuck",
    tags: ["tier1", "digit"],
    description: '5 as string (literal shortcut)',
  },
  {
    id: "digit_6",
    output: "6",
    role: "digit_6",
    expression: '"6"',
    pure: false,
    kind: "jsfuck",
    tags: ["tier1", "digit"],
    description: '6 as string (literal shortcut)',
  },
  {
    id: "digit_7",
    output: "7",
    role: "digit_7",
    expression: '"7"',
    pure: false,
    kind: "jsfuck",
    tags: ["tier1", "digit"],
    description: '7 as string (literal shortcut)',
  },
  {
    id: "digit_8",
    output: "8",
    role: "digit_8",
    expression: '"8"',
    pure: false,
    kind: "jsfuck",
    tags: ["tier1", "digit"],
    description: '8 as string (literal shortcut)',
  },
  {
    id: "digit_9",
    output: "9",
    role: "digit_9",
    expression: '"9"',
    pure: false,
    kind: "jsfuck",
    tags: ["tier1", "digit"],
    description: '9 as string (literal shortcut)',
  },
  // digit 5-9: strict 版（pure arithmetic）
  {
    id: "digit_5_strict",
    output: "5",
    role: "digit_5",
    expression: "!![]+!![]+!![]+!![]+!![]+[]",
    pure: true,
    kind: "jsfuck",
    tags: ["tier1", "digit", "strict"],
    description: "5 as string (pure JSFuck)",
  },
  {
    id: "digit_6_strict",
    output: "6",
    role: "digit_6",
    expression: "!![]+!![]+!![]+!![]+!![]+!![]+[]",
    pure: true,
    kind: "jsfuck",
    tags: ["tier1", "digit", "strict"],
    description: "6 as string (pure JSFuck)",
  },
  {
    id: "digit_7_strict",
    output: "7",
    role: "digit_7",
    expression: "!![]+!![]+!![]+!![]+!![]+!![]+!![]+[]",
    pure: true,
    kind: "jsfuck",
    tags: ["tier1", "digit", "strict"],
    description: "7 as string (pure JSFuck)",
  },
  {
    id: "digit_8_strict",
    output: "8",
    role: "digit_8",
    expression: "!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[]",
    pure: true,
    kind: "jsfuck",
    tags: ["tier1", "digit", "strict"],
    description: "8 as string (pure JSFuck)",
  },
  {
    id: "digit_9_strict",
    output: "9",
    role: "digit_9",
    expression: "!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[]",
    pure: true,
    kind: "jsfuck",
    tags: ["tier1", "digit", "strict"],
    description: "9 as string (pure JSFuck)",
  },
  // ===== primitive strings as whole =====
  {
    id: "str_false",
    output: "false",
    role: "str_false",
    expression: "(![]+[])",
    pure: true,
    kind: "jsfuck",
    tags: ["tier1", "primitive_str"],
    description: 'false coerced to string = "false"',
  },
  {
    id: "str_true",
    output: "true",
    role: "str_true",
    expression: "(!![]+[])",
    pure: true,
    kind: "jsfuck",
    tags: ["tier1", "primitive_str"],
    description: 'true coerced to string = "true"',
  },
  {
    id: "str_nan",
    output: "NaN",
    role: "str_nan",
    expression: "(+{}+[])",
    pure: true,
    kind: "jsfuck",
    tags: ["tier1", "primitive_str"],
    description: 'NaN coerced to string = "NaN"',
  },
  {
    id: "str_infinity",
    output: "Infinity",
    role: "str_infinity",
    expression: "(1/0+[])",
    pure: true,
    kind: "jsfuck",
    tags: ["tier1", "primitive_str"],
    description: 'Infinity coerced to string = "Infinity"',
  },
  {
    id: "str_undefined",
    output: "undefined",
    role: "str_undefined",
    expression: "([][+[]]+[])",
    pure: true,
    kind: "jsfuck",
    tags: ["tier1", "primitive_str"],
    description: 'undefined coerced to string = "undefined"',
  },
];

export default TIER1;
