import type { Pattern } from "../types.js";

// Tier 1: difficulty 1.0~1.5
// Characters from: false/true/undefined/NaN/Infinity/digit-arithmetic
// Note: primitives must be coerced to string before indexing
// e.g. (![]+[])[0] = "false"[0] = 'f'  NOT  (![])[0] which is undefined

const TIER1: Pattern[] = [
  // ===== from "false" (![]+[]) =====
  {
    id: "char_f",
    output: "f",
    expression: "(![]+[])[+[]]",
    kind: "jsfuck",
    difficulty: 1.0,
    weight: 2,
    cost: 13,
    tags: ["tier1", "from_false", "readable"],
    trapFor: [],
    requires: [],
    description: '"false"[0]',
  },
  {
    id: "char_a",
    output: "a",
    expression: "(![]+[])[1]",
    kind: "jsfuck",
    difficulty: 1.0,
    weight: 2,
    cost: 11,
    tags: ["tier1", "from_false", "readable"],
    trapFor: [],
    requires: [],
    description: '"false"[1]',
  },
  {
    id: "char_l",
    output: "l",
    expression: "(![]+[])[2]",
    kind: "jsfuck",
    difficulty: 1.0,
    weight: 2,
    cost: 11,
    tags: ["tier1", "from_false", "readable"],
    trapFor: [],
    requires: [],
    description: '"false"[2]',
  },
  {
    id: "char_s",
    output: "s",
    expression: "(![]+[])[3]",
    kind: "jsfuck",
    difficulty: 1.0,
    weight: 2,
    cost: 11,
    tags: ["tier1", "from_false", "readable"],
    trapFor: [],
    requires: [],
    description: '"false"[3]',
  },
  {
    id: "char_e",
    output: "e",
    expression: "(![]+[])[4]",
    kind: "jsfuck",
    difficulty: 1.0,
    weight: 2,
    cost: 11,
    tags: ["tier1", "from_false", "readable"],
    trapFor: [],
    requires: [],
    description: '"false"[4]',
  },
  // ===== from "true" (!![]+[]) =====
  {
    id: "char_t",
    output: "t",
    expression: "(!![]+[])[+[]]",
    kind: "jsfuck",
    difficulty: 1.0,
    weight: 2,
    cost: 14,
    tags: ["tier1", "from_true", "readable"],
    trapFor: [],
    requires: [],
    description: '"true"[0]',
  },
  {
    id: "char_r",
    output: "r",
    expression: "(!![]+[])[1]",
    kind: "jsfuck",
    difficulty: 1.0,
    weight: 2,
    cost: 12,
    tags: ["tier1", "from_true", "readable"],
    trapFor: [],
    requires: [],
    description: '"true"[1]',
  },
  {
    id: "char_u",
    output: "u",
    expression: "(!![]+[])[2]",
    kind: "jsfuck",
    difficulty: 1.0,
    weight: 2,
    cost: 12,
    tags: ["tier1", "from_true", "readable"],
    trapFor: [],
    requires: [],
    description: '"true"[2]',
  },
  // ===== from "undefined" ([][+[]]+[]) =====
  {
    id: "char_n",
    output: "n",
    expression: "([][+[]]+[])[1]",
    kind: "jsfuck",
    difficulty: 1.0,
    weight: 2,
    cost: 15,
    tags: ["tier1", "from_undefined", "readable"],
    trapFor: [],
    requires: [],
    description: '"undefined"[1]',
  },
  {
    id: "char_d",
    output: "d",
    expression: "([][+[]]+[])[2]",
    kind: "jsfuck",
    difficulty: 1.0,
    weight: 2,
    cost: 15,
    tags: ["tier1", "from_undefined", "readable"],
    trapFor: [],
    requires: [],
    description: '"undefined"[2]',
  },
  {
    id: "char_i",
    output: "i",
    expression: "([][+[]]+[])[5]",
    kind: "jsfuck",
    difficulty: 1.0,
    weight: 2,
    cost: 15,
    tags: ["tier1", "from_undefined", "readable"],
    trapFor: [],
    requires: [],
    description: '"undefined"[5]',
  },
  // ===== from "NaN" (+{}+[]) =====
  {
    id: "char_N_upper",
    output: "N",
    expression: "(+{}+[])[+[]]",
    kind: "jsfuck",
    difficulty: 1.2,
    weight: 1,
    cost: 13,
    tags: ["tier1", "from_nan", "uppercase"],
    trapFor: ["char_n"],
    requires: [],
    description: '"NaN"[0] — uppercase N, easy to confuse with lowercase n',
  },
  {
    id: "char_a_nan",
    output: "a",
    expression: "(+{}+[])[1]",
    kind: "jsfuck",
    difficulty: 1.2,
    weight: 1,
    cost: 11,
    tags: ["tier1", "from_nan"],
    trapFor: ["char_a"],
    requires: [],
    description: '"NaN"[1] — alternate source for a',
  },
  // ===== from "Infinity" (1/0+[]) =====
  {
    id: "char_I_upper",
    output: "I",
    expression: "(1/0+[])[+[]]",
    kind: "jsfuck",
    difficulty: 1.3,
    weight: 1,
    cost: 13,
    tags: ["tier1", "from_infinity", "uppercase"],
    trapFor: ["char_i"],
    requires: [],
    description: '"Infinity"[0] — uppercase I, easy to confuse with lowercase i',
  },
  {
    id: "char_y",
    output: "y",
    expression: "(1/0+[])[7]",
    kind: "jsfuck",
    difficulty: 1.3,
    weight: 1,
    cost: 11,
    tags: ["tier1", "from_infinity"],
    trapFor: [],
    requires: [],
    description: '"Infinity"[7]',
  },
  // ===== digit strings via arithmetic =====
  {
    id: "digit_0",
    output: "0",
    expression: "+[]+[]",
    kind: "jsfuck",
    difficulty: 1.0,
    weight: 3,
    cost: 6,
    tags: ["tier1", "digit", "readable"],
    trapFor: [],
    requires: [],
    description: "0 coerced to string",
  },
  {
    id: "digit_1",
    output: "1",
    expression: "+!![]+[]",
    kind: "jsfuck",
    difficulty: 1.0,
    weight: 3,
    cost: 7,
    tags: ["tier1", "digit", "readable"],
    trapFor: [],
    requires: [],
    description: "1 coerced to string",
  },
  {
    id: "digit_2",
    output: "2",
    expression: "!![]+!![]+[]",
    kind: "jsfuck",
    difficulty: 1.0,
    weight: 3,
    cost: 12,
    tags: ["tier1", "digit"],
    trapFor: [],
    requires: [],
    description: "true+true coerced to string",
  },
  {
    id: "digit_3",
    output: "3",
    expression: "!![]+!![]+!![]+[]",
    kind: "jsfuck",
    difficulty: 1.0,
    weight: 3,
    cost: 17,
    tags: ["tier1", "digit"],
    trapFor: [],
    requires: [],
    description: "true*3 coerced to string",
  },
  {
    id: "digit_4",
    output: "4",
    expression: "!![]+!![]+!![]+!![]+[]",
    kind: "jsfuck",
    difficulty: 1.0,
    weight: 3,
    cost: 22,
    tags: ["tier1", "digit"],
    trapFor: [],
    requires: [],
    description: "true*4 coerced to string",
  },
  {
    id: "digit_5",
    output: "5",
    expression: "!![]+!![]+!![]+!![]+!![]+[]",
    kind: "jsfuck",
    difficulty: 1.0,
    weight: 3,
    cost: 27,
    tags: ["tier1", "digit"],
    trapFor: [],
    requires: [],
    description: "true*5 coerced to string",
  },
  {
    id: "digit_6",
    output: "6",
    expression: "!![]+!![]+!![]+!![]+!![]+!![]+[]",
    kind: "jsfuck",
    difficulty: 1.0,
    weight: 3,
    cost: 32,
    tags: ["tier1", "digit"],
    trapFor: [],
    requires: [],
    description: "true*6 coerced to string",
  },
  {
    id: "digit_7",
    output: "7",
    expression: "!![]+!![]+!![]+!![]+!![]+!![]+!![]+[]",
    kind: "jsfuck",
    difficulty: 1.0,
    weight: 3,
    cost: 37,
    tags: ["tier1", "digit"],
    trapFor: [],
    requires: [],
    description: "true*7 coerced to string",
  },
  {
    id: "digit_8",
    output: "8",
    expression: "!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[]",
    kind: "jsfuck",
    difficulty: 1.0,
    weight: 3,
    cost: 42,
    tags: ["tier1", "digit"],
    trapFor: [],
    requires: [],
    description: "true*8 coerced to string",
  },
  {
    id: "digit_9",
    output: "9",
    expression: "!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+!![]+[]",
    kind: "jsfuck",
    difficulty: 1.0,
    weight: 3,
    cost: 47,
    tags: ["tier1", "digit"],
    trapFor: [],
    requires: [],
    description: "true*9 coerced to string",
  },
  // ===== from "[object Object]" ([]+{}) =====
  {
    id: "char_O_upper",
    output: "O",
    expression: "([]+{})[8]",
    kind: "jsfuck",
    difficulty: 1.4,
    weight: 1,
    cost: 10,
    tags: ["tier1", "from_obj", "uppercase"],
    trapFor: ["char_o"],
    requires: [],
    description: '"[object Object]"[8] — uppercase O',
  },
  // ===== space from [object Object] =====
  {
    id: "char_space",
    output: " ",
    expression: "([]+{})[7]",
    kind: "jsfuck",
    difficulty: 1.4,
    weight: 1,
    cost: 10,
    tags: ["tier1", "symbol"],
    trapFor: [],
    requires: [],
    description: '"[object Object]"[7] — space character',
  },
  // ===== c and o from fill function string =====
  // ([]["fill"]+[]) = "function fill() { [native code] }"
  // Requires f(0),i(1),l(2),l(3) from tier1 to build "fill" key
  {
    id: "char_c",
    output: "c",
    expression:
      "([][(![]+[])[+[]]+([][+[]]+[])[5]+(![]+[])[2]+(![]+[])[2]]+[])[3]",
    kind: "jsfuck",
    difficulty: 1.4,
    weight: 2,
    cost: 51,
    tags: ["tier1", "from_fill_fn"],
    trapFor: [],
    requires: ["char_f", "char_i", "char_l"],
    description: '"function fill(){[native code]}"[3] — c',
  },
  {
    id: "char_o",
    output: "o",
    expression:
      "([][(![]+[])[+[]]+([][+[]]+[])[5]+(![]+[])[2]+(![]+[])[2]]+[])[6]",
    kind: "jsfuck",
    difficulty: 1.4,
    weight: 2,
    cost: 51,
    tags: ["tier1", "from_fill_fn"],
    trapFor: [],
    requires: ["char_f", "char_i", "char_l"],
    description: '"function fill(){[native code]}"[6] — o',
  },
];

export default TIER1;
